FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD jenkins.jar /opt/jenkins/
EXPOSE 8080
WORKDIR /opt/jenkins/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "jenkins.jar"]
